// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessagesSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesSummary) Reset() {
	*x = MessagesSummary{}
	mi := &file_api_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesSummary) ProtoMessage() {}

func (x *MessagesSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesSummary.ProtoReflect.Descriptor instead.
func (*MessagesSummary) Descriptor() ([]byte, []int) {
	return file_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MessagesSummary) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_messages_proto protoreflect.FileDescriptor

const file_api_messages_proto_rawDesc = "" +
	"\n" +
	"\x12api/messages.proto\x12\bmessages\x1a\x1bgoogle/protobuf/empty.proto\"'\n" +
	"\x0fMessagesSummary\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count2U\n" +
	"\bMessages\x12I\n" +
	"\x12GetMessagesSummary\x12\x16.google.protobuf.Empty\x1a\x19.messages.MessagesSummary\"\x00B\x0eZ\fpkg/messagesb\x06proto3"

var (
	file_api_messages_proto_rawDescOnce sync.Once
	file_api_messages_proto_rawDescData []byte
)

func file_api_messages_proto_rawDescGZIP() []byte {
	file_api_messages_proto_rawDescOnce.Do(func() {
		file_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_messages_proto_rawDesc), len(file_api_messages_proto_rawDesc)))
	})
	return file_api_messages_proto_rawDescData
}

var file_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_messages_proto_goTypes = []any{
	(*MessagesSummary)(nil), // 0: messages.MessagesSummary
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_api_messages_proto_depIdxs = []int32{
	1, // 0: messages.Messages.GetMessagesSummary:input_type -> google.protobuf.Empty
	0, // 1: messages.Messages.GetMessagesSummary:output_type -> messages.MessagesSummary
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_messages_proto_init() }
func file_api_messages_proto_init() {
	if File_api_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_messages_proto_rawDesc), len(file_api_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_messages_proto_goTypes,
		DependencyIndexes: file_api_messages_proto_depIdxs,
		MessageInfos:      file_api_messages_proto_msgTypes,
	}.Build()
	File_api_messages_proto = out.File
	file_api_messages_proto_goTypes = nil
	file_api_messages_proto_depIdxs = nil
}
